import { User, Branch, Workflow, Attendance, Payroll, Analytics } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'admin',
    password: 'admin123',
    role: 'admin',
    name: 'Admin User',
    email: 'admin@company.com',
  },
  {
    id: '2',
    username: 'staff',
    password: 'staff123',
    role: 'staff',
    name: 'Staff User',
    email: 'staff@company.com',
    branchId: 'branch-1',
  },
];

export const mockBranches: Branch[] = [
  {
    id: 'branch-1',
    name: 'Downtown Branch',
    location: 'New York, NY',
    manager: 'John Smith',
    staff: 25,
    status: 'active',
  },
  {
    id: 'branch-2',
    name: 'Uptown Branch',
    location: 'Los Angeles, CA',
    manager: 'Sarah Johnson',
    staff: 18,
    status: 'active',
  },
  {
    id: 'branch-3',
    name: 'Eastside Branch',
    location: 'Chicago, IL',
    manager: 'Michael Brown',
    staff: 22,
    status: 'active',
  },
  {
    id: 'branch-4',
    name: 'Westside Branch',
    location: 'Houston, TX',
    manager: 'Emily Davis',
    staff: 15,
    status: 'inactive',
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: 'wf-1',
    title: 'Q4 Sales Report',
    branchId: 'branch-1',
    branchName: 'Downtown Branch',
    assignedTo: 'Staff User',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2025-10-30',
    progress: 65,
  },
  {
    id: 'wf-2',
    title: 'Inventory Audit',
    branchId: 'branch-1',
    branchName: 'Downtown Branch',
    assignedTo: 'Alice Cooper',
    status: 'completed',
    priority: 'medium',
    dueDate: '2025-10-25',
    progress: 100,
  },
  {
    id: 'wf-3',
    title: 'Customer Feedback Analysis',
    branchId: 'branch-2',
    branchName: 'Uptown Branch',
    assignedTo: 'Bob Wilson',
    status: 'pending',
    priority: 'low',
    dueDate: '2025-11-05',
    progress: 0,
  },
  {
    id: 'wf-4',
    title: 'Staff Training Program',
    branchId: 'branch-3',
    branchName: 'Eastside Branch',
    assignedTo: 'Carol White',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2025-10-28',
    progress: 45,
  },
  {
    id: 'wf-5',
    title: 'Security System Upgrade',
    branchId: 'branch-2',
    branchName: 'Uptown Branch',
    assignedTo: 'David Lee',
    status: 'overdue',
    priority: 'high',
    dueDate: '2025-10-20',
    progress: 30,
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: 'att-1',
    userId: '2',
    userName: 'Staff User',
    branchId: 'branch-1',
    branchName: 'Downtown Branch',
    date: '2025-10-26',
    checkIn: '09:00 AM',
    checkOut: '05:00 PM',
    status: 'present',
    hoursWorked: 8,
  },
  {
    id: 'att-2',
    userId: '2',
    userName: 'Staff User',
    branchId: 'branch-1',
    branchName: 'Downtown Branch',
    date: '2025-10-25',
    checkIn: '09:15 AM',
    checkOut: '05:00 PM',
    status: 'late',
    hoursWorked: 7.75,
  },
  {
    id: 'att-3',
    userId: '3',
    userName: 'Alice Cooper',
    branchId: 'branch-1',
    branchName: 'Downtown Branch',
    date: '2025-10-26',
    checkIn: '09:00 AM',
    checkOut: '05:00 PM',
    status: 'present',
    hoursWorked: 8,
  },
  {
    id: 'att-4',
    userId: '4',
    userName: 'Bob Wilson',
    branchId: 'branch-2',
    branchName: 'Uptown Branch',
    date: '2025-10-26',
    checkIn: '09:00 AM',
    checkOut: '01:00 PM',
    status: 'half-day',
    hoursWorked: 4,
  },
];

export const mockPayroll: Payroll[] = [
  {
    id: 'pay-1',
    userId: '2',
    userName: 'Staff User',
    branchId: 'branch-1',
    branchName: 'Downtown Branch',
    month: 'October 2025',
    baseSalary: 4500,
    allowances: 500,
    deductions: 450,
    netSalary: 4550,
    status: 'processed',
  },
  {
    id: 'pay-2',
    userId: '3',
    userName: 'Alice Cooper',
    branchId: 'branch-1',
    branchName: 'Downtown Branch',
    month: 'October 2025',
    baseSalary: 4200,
    allowances: 400,
    deductions: 420,
    netSalary: 4180,
    status: 'paid',
  },
  {
    id: 'pay-3',
    userId: '4',
    userName: 'Bob Wilson',
    branchId: 'branch-2',
    branchName: 'Uptown Branch',
    month: 'October 2025',
    baseSalary: 4000,
    allowances: 300,
    deductions: 400,
    netSalary: 3900,
    status: 'pending',
  },
];

export const mockAnalytics: Analytics = {
  totalBranches: 4,
  totalStaff: 80,
  totalWorkflows: 45,
  completedWorkflows: 28,
  attendanceRate: 92.5,
  payrollProcessed: 75,
};
